/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author dgalvarez
 */
public class ViewProduct extends javax.swing.JFrame {

    /**
     * Creates new form ViewProduct
     */
    public ViewProduct() {
        initComponents();
        this.setVisible(true);
        this.UpdateDialog.setSize(300,280);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDialog = new javax.swing.JDialog();
        ProductoToUpdateLabel = new javax.swing.JLabel();
        NameToUpdate = new javax.swing.JLabel();
        PriceToUpdate = new javax.swing.JLabel();
        InventoryToUpdate = new javax.swing.JLabel();
        NameToUpdateField = new javax.swing.JTextField();
        PriceToUpdateField = new javax.swing.JTextField();
        InventoryToUpdateField = new javax.swing.JTextField();
        UpdateDialogButton = new javax.swing.JButton();
        PANELPRINCIPAL = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        PanesAdd = new javax.swing.JPanel();
        NameProductLabel = new javax.swing.JLabel();
        PriceProductLabel = new javax.swing.JLabel();
        InventoryProductLabel = new javax.swing.JLabel();
        NameProductField = new javax.swing.JTextField();
        PriceProductField = new javax.swing.JTextField();
        InventoryProductField = new javax.swing.JTextField();
        AddProductButton = new javax.swing.JButton();
        InfoProductButton = new javax.swing.JButton();
        UpdateProductButton = new javax.swing.JButton();
        DeleteProductButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportTablePanel = new javax.swing.JTable();

        UpdateDialog.setTitle("Actualizar producto");

        ProductoToUpdateLabel.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        ProductoToUpdateLabel.setText("Ingrese los nuevos valores");

        NameToUpdate.setText("Nombre");

        PriceToUpdate.setText("Precio");

        InventoryToUpdate.setText("Inventario");

        PriceToUpdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceToUpdateFieldActionPerformed(evt);
            }
        });

        UpdateDialogButton.setText("Actualizar Producto");

        javax.swing.GroupLayout UpdateDialogLayout = new javax.swing.GroupLayout(UpdateDialog.getContentPane());
        UpdateDialog.getContentPane().setLayout(UpdateDialogLayout);
        UpdateDialogLayout.setHorizontalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ProductoToUpdateLabel)
                .addGap(51, 51, 51))
            .addGroup(UpdateDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UpdateDialogButton)
                    .addGroup(UpdateDialogLayout.createSequentialGroup()
                        .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PriceToUpdate)
                            .addComponent(NameToUpdate)
                            .addComponent(InventoryToUpdate))
                        .addGap(32, 32, 32)
                        .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameToUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InventoryToUpdateField)
                                .addComponent(PriceToUpdateField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        UpdateDialogLayout.setVerticalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductoToUpdateLabel)
                .addGap(30, 30, 30)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameToUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameToUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceToUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceToUpdate))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InventoryToUpdate)
                    .addComponent(InventoryToUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateDialogButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto5 Inventario de productos");

        PANELPRINCIPAL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TITULO.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        TITULO.setText("!BIENVENIDO A LA APP DE INVENTARIO");

        PanesAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar nuevo Producto"));

        NameProductLabel.setText("Nombre");

        PriceProductLabel.setText("Precio");

        InventoryProductLabel.setText("Iventario");

        AddProductButton.setText("Agregar Producto");

        javax.swing.GroupLayout PanesAddLayout = new javax.swing.GroupLayout(PanesAdd);
        PanesAdd.setLayout(PanesAddLayout);
        PanesAddLayout.setHorizontalGroup(
            PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanesAddLayout.createSequentialGroup()
                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanesAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanesAddLayout.createSequentialGroup()
                                .addComponent(NameProductLabel)
                                .addGap(51, 51, 51)
                                .addComponent(NameProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanesAddLayout.createSequentialGroup()
                                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InventoryProductLabel)
                                    .addComponent(PriceProductLabel))
                                .addGap(47, 47, 47)
                                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InventoryProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanesAddLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(AddProductButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanesAddLayout.setVerticalGroup(
            PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanesAddLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameProductLabel)
                    .addComponent(NameProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceProductLabel)
                    .addComponent(PriceProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanesAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventoryProductLabel)
                    .addComponent(InventoryProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InfoProductButton.setText("Informe");

        UpdateProductButton.setText("Actualizar producto");
        UpdateProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductButtonActionPerformed(evt);
            }
        });

        DeleteProductButton.setText("Borrar Producto");

        ReportTablePanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Inventario"
            }
        ));
        ReportTablePanel.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(ReportTablePanel);

        javax.swing.GroupLayout PANELPRINCIPALLayout = new javax.swing.GroupLayout(PANELPRINCIPAL);
        PANELPRINCIPAL.setLayout(PANELPRINCIPALLayout);
        PANELPRINCIPALLayout.setHorizontalGroup(
            PANELPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELPRINCIPALLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(PANELPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(PANELPRINCIPALLayout.createSequentialGroup()
                        .addComponent(DeleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InfoProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(PANELPRINCIPALLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(PanesAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELPRINCIPALLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TITULO)
                .addGap(65, 65, 65))
        );
        PANELPRINCIPALLayout.setVerticalGroup(
            PANELPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELPRINCIPALLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(TITULO)
                .addGap(33, 33, 33)
                .addComponent(PanesAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PANELPRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateProductButton)
                    .addComponent(DeleteProductButton)
                    .addComponent(InfoProductButton))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProductButtonActionPerformed

    private void PriceToUpdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceToUpdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceToUpdateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewProduct().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JButton DeleteProductButton;
    private javax.swing.JButton InfoProductButton;
    private javax.swing.JTextField InventoryProductField;
    private javax.swing.JLabel InventoryProductLabel;
    private javax.swing.JLabel InventoryToUpdate;
    private javax.swing.JTextField InventoryToUpdateField;
    private javax.swing.JTextField NameProductField;
    private javax.swing.JLabel NameProductLabel;
    private javax.swing.JLabel NameToUpdate;
    private javax.swing.JTextField NameToUpdateField;
    private javax.swing.JPanel PANELPRINCIPAL;
    private javax.swing.JPanel PanesAdd;
    private javax.swing.JTextField PriceProductField;
    private javax.swing.JLabel PriceProductLabel;
    private javax.swing.JLabel PriceToUpdate;
    private javax.swing.JTextField PriceToUpdateField;
    private javax.swing.JLabel ProductoToUpdateLabel;
    private javax.swing.JTable ReportTablePanel;
    private javax.swing.JLabel TITULO;
    private javax.swing.JDialog UpdateDialog;
    private javax.swing.JButton UpdateDialogButton;
    private javax.swing.JButton UpdateProductButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

////////////////////////////// PRODUCTS ////////////////////////////////////////    
//Getters and Setters of the Buttons
    public JButton getAddProductButton() {
        return AddProductButton;
    }

    public JButton getDeleteProductButton() {
        return DeleteProductButton;
    }

    public JButton getInfoProductButton() {
        return InfoProductButton;
    }

    public JButton getUpdateProductButton() {
        return UpdateProductButton;
    }

    public void setUpdateProductButton(JButton UpdateProductButton) {
        this.UpdateProductButton = UpdateProductButton;
    }

    public void setAddProductButton(JButton AddProductButton) {
        this.AddProductButton = AddProductButton;
    }

    public void setDeleteProductButton(JButton DeleteProductButton) {
        this.DeleteProductButton = DeleteProductButton;
    }

    public void setInfoProductButton(JButton InfoProductButton) {
        this.InfoProductButton = InfoProductButton;
    }
//Getters and Setters of the Fields

    public JTextField getInventoryProductField() {
        return InventoryProductField;
    }

    public void setInventoryProductField(JTextField InventoryProductField) {
        this.InventoryProductField = InventoryProductField;
    }

    public JTextField getNameProductField() {
        return NameProductField;
    }

    public void setNameProductField(JTextField NameProductField) {
        this.NameProductField = NameProductField;
    }

    public JTextField getPriceProductField() {
        return PriceProductField;
    }

    public void setPriceProductField(JTextField PriceProductField) {
        this.PriceProductField = PriceProductField;
    }
    //Getter and Setter of th Table

    public JTable getReportTableProducts() {
        return ReportTablePanel;
    }

    public void setReportTableProducts(JTable ReportTableProducts) {
        this.ReportTablePanel = ReportTableProducts;
    }
 
////////////////////////////// PRODUCTS TO UPDATE //////////////////////////////

    //Getter and Setter Button

    public JButton getUpdateDialogButton() {
        return UpdateDialogButton;
    }

    public void setUpdateDialogButton(JButton UpdateDialogButton) {
        this.UpdateDialogButton = UpdateDialogButton;
    }


    //Getters and Setters ToUpdate Field

    public JTextField getInventoryToUpdateField() {
        return InventoryToUpdateField;
    }

    public void setInventoryToUpdateField(JTextField InventoryToUpdateField) {
        this.InventoryToUpdateField = InventoryToUpdateField;
    }

    public JTextField getNameToUpdateField() {
        return NameToUpdateField;
    }

    public void setNameToUpdateField(JTextField NameToUpdateField) {
        this.NameToUpdateField = NameToUpdateField;
    }

    public JTextField getPriceToUpdateField() {
        return PriceToUpdateField;
    }

    public void setPriceToUpdateField(JTextField PriceToUpdateField) {
        this.PriceToUpdateField = PriceToUpdateField;
    }
    // Getter and Setter UpdateDialog

    public JDialog getUpdateDialog() {
        return UpdateDialog;
    }

    public void setUpdateDialog(JDialog UpdateDialog) {
        this.UpdateDialog = UpdateDialog;
    }
    
}
